Ruby Capstone - Final Code Review
eri8-9/Catalog_of_my_things pull request #69
Opened 2021-11-11 17:29 UTC by tiagorahal

### Ruby Capstone - Final Code Review.

2021-11-11 19:12 UTC, e71az requested changes
# Status:  Changes Required ♻️
_Check the comments under the review_
<hr>

Hello @tiagorahal @eri8-9, I am Elias, your reviewer for this PR

Well done so far with your project!

Almost everything is correctly set up, I really liked your project presentation, the project works great, the documentation is awesome and you even add the extra requirements for a bigger team, keep it up!

I will mention to you a small summary of things that need to be changed in order to keep moving:

- [ ] In your video you forgot to highlight a piece of code that was interesting to each one or made you proud, please record a new video just mentioning this, you don't have to explain everything else again.
- [x] Please check some typos in your console navigation and messages.
- [ ] Please check comments below for additional requirements.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please correct those issues and send another review request, good luck, and well done so far! 

Code review by Elias Castañeda

_(Feel free to leave any questions or comments in the PR thread if something is not 100% clear)_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/restricted?return_to=https%3A%2F%2Fmicroverse.zendesk.com%2Fhc%2Fen-us%2Farticles%2F1500004088561) you have a limited number of code reviews per project (you can check the exact number in your Dashboard). If you think that the code review was not fair, you can [request a second opinion using this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-11-11 19:12 UTC, eliasecasta commented on src/classes/item.rb
> +    @archived = can_be_archived?
- [x] This method should do nothing if the result of the can_be_archived?() method is false, please change the logic adding an if evaluating the result of can_be_archived?. Right now, if it is false, it will be assigned to the @archived variable anyways.

2021-11-11 19:12 UTC, eliasecasta commented on src/classes/db.rb
> +  def save(data, file_name)
- [x] All public methods in all classes should have unit tests, please also add tests to your db.rb and item.rb classes to comply with the project requirements.

2021-11-11 19:12 UTC, e71az commented on src/modules/create_items.rb
> +    puts "\nIt's the movie silent?"
- [ ] If I try to select 1 for yes, I get my movie as silent: false anyways, please take a look at this small bug.

2021-11-11 19:12 UTC, e71az commented on README.md
> +
- [ ] [OPTIONAL] Your Readme will look even better if you add a small screenshot of your application, even if it is only a ss from the navigation interface 👍

2021-11-12 16:55 UTC, mikethreels approved these changes
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 :
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-12 16:57 UTC, merged